services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ktor_api
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      DB_URL: jdbc:mariadb://mariadb:3306/ktor_db
      DB_DRIVER: org.mariadb.jdbc.Driver
      DB_USER: ktor_user
      DB_PASSWORD: ktor_pass
      JWT_SECRET: super_secret_key
      JWT_ISSUER: domain.com
      JWT_AUDIENCE: ktor_audience
      JWT_REALM: ktor_realm
    ports:
      - "8080:8080"

  mariadb:
    image: mariadb:11.8
    container_name: ktor_mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root123
      MARIADB_DATABASE: ktor_db
      MARIADB_USER: ktor_user
      MARIADB_PASSWORD: ktor_pass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-uroot", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer:4.8.1
    container_name: ktor_adminer
    restart: unless-stopped
    depends_on:
      - mariadb
    ports:
      - "8081:8080"

volumes:
  mariadb_data:
