ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080
        host: 0.0.0.0
database:
    jdbcUrl: ${?DB_URL}
    driverClassName: ${?DB_DRIVER}
    username: ${?DB_USER}
    password: ${?DB_PASSWORD}
jwt:
    secret: ${?JWT_SECRET}
    issuer: ${?JWT_ISSUER}
    audience: ${?JWT_AUDIENCE}
    realm: ${?JWT_REALM}
